"""Generates the per-repo docker-compose file for the Odoo test environment
(technical-spec.md §6.1).

Per repo: one Odoo container `taskman-odoo-<repo>` + one Postgres `taskman-db-<repo>`,
both on the shared `taskman-net` bridge network. The Odoo service's entrypoint is a
sleep (the image's own `ENTRYPOINT ["sleep", "infinity"]` — see docker/odoo-test/Dockerfile);
the actual `odoo-bin` process is started/killed/restarted per deploy cycle via `docker exec`
(§6.2), independent of the container's own lifetime.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml


@dataclass(frozen=True)
class RepoMounts:
    """Host paths that make up one repo's addons_path (technical-spec.md §3.1/§6.1).
    `enterprise_dir` and `design_themes_dir` are optional — the demo fixture has no
    design-themes checkout, and a client repo's own external-addons/oca-addons are
    optional too (§3.1 note: "not all repos have this one")."""

    odoo_dir: Path
    repo_dir: Path
    enterprise_dir: Path | None = None
    design_themes_dir: Path | None = None
    addons_path_extra: list[str] = field(default_factory=list)


def addons_path(mounts: RepoMounts) -> list[str]:
    """Order per spec §6.1: odoo/addons, enterprise, design-themes, then this repo's
    own addons/, external-addons/, oca-addons/ (whichever exist), then addons_path_extra."""
    parts: list[str] = [str(mounts.odoo_dir / "addons")]
    if mounts.enterprise_dir is not None:
        parts.append(str(mounts.enterprise_dir))
    if mounts.design_themes_dir is not None:
        parts.append(str(mounts.design_themes_dir))
    for sub in ("addons", "external-addons", "oca-addons"):
        candidate = mounts.repo_dir / sub
        if candidate.is_dir():
            parts.append(f"/repos/{sub}")
    parts.extend(mounts.addons_path_extra)
    return parts


CONTAINER_ODOO_DIR = "/repos/odoo"
CONTAINER_ENTERPRISE_DIR = "/repos/enterprise"
CONTAINER_REPO_DIR = "/repos/repo"
CONTAINER_CONF_PATH = "/etc/odoo/odoo.conf"


def container_addons_path(mounts: RepoMounts) -> str:
    """Same as addons_path() but expressed in container-internal mount paths
    (CONTAINER_*_DIR), for writing into the generated odoo.conf."""
    parts: list[str] = [f"{CONTAINER_ODOO_DIR}/addons"]
    if mounts.enterprise_dir is not None:
        parts.append(CONTAINER_ENTERPRISE_DIR)
    for sub in ("addons", "external-addons", "oca-addons"):
        if (mounts.repo_dir / sub).is_dir():
            parts.append(f"{CONTAINER_REPO_DIR}/{sub}")
    parts.extend(mounts.addons_path_extra)
    return ",".join(parts)


def render_odoo_conf(mounts: RepoMounts, *, db_name: str, db_container: str, db_user: str = "odoo",
                      db_password: str = "odoo", http_port: int = 8069) -> str:
    lines = [
        "[options]",
        f"addons_path = {container_addons_path(mounts)}",
        f"db_host = {db_container}",
        "db_port = 5432",
        f"db_user = {db_user}",
        f"db_password = {db_password}",
        f"dbfilter = ^{db_name}$",
        f"http_port = {http_port}",
        "without_demo = all",
        "list_db = False",
    ]
    return "\n".join(lines) + "\n"


def render_compose(
    *,
    repo: str,
    image: str,
    network: str,
    mounts: RepoMounts,
    conf_host_path: Path,
    db_user: str = "odoo",
    db_password: str = "odoo",
) -> str:
    """Renders the docker-compose.yml text for one repo's Odoo+Postgres pair.
    `conf_host_path` is a host file (generated by render_odoo_conf, written by the
    caller) bind-mounted read-only into the odoo container at CONTAINER_CONF_PATH."""
    odoo_container = f"taskman-odoo-{repo}"
    db_container = f"taskman-db-{repo}"

    volumes = [
        f"{mounts.odoo_dir}:{CONTAINER_ODOO_DIR}:ro",
        f"{mounts.repo_dir}:{CONTAINER_REPO_DIR}:rw",
        f"{conf_host_path}:{CONTAINER_CONF_PATH}:ro",
    ]
    if mounts.enterprise_dir is not None:
        volumes.insert(1, f"{mounts.enterprise_dir}:{CONTAINER_ENTERPRISE_DIR}:ro")

    compose = {
        "networks": {network: {"external": True}},
        "services": {
            "odoo": {
                "container_name": odoo_container,
                "image": image,
                "networks": [network],
                "volumes": volumes,
                "tty": True,
            },
            "db": {
                "container_name": db_container,
                "image": "postgres:16",
                "networks": [network],
                "environment": {
                    "POSTGRES_USER": db_user,
                    "POSTGRES_PASSWORD": db_password,
                    "POSTGRES_DB": "postgres",
                },
            },
        },
    }
    return yaml.safe_dump(compose, sort_keys=False)
